###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{

    "alumno": "Cesar A",
    "edad": 23,
    "cuenta": "20168095",
    "correo": "CesarA@email.com"

}


### Get all users
GET http://localhost:9000/api/users HTTP/1.1

### Get 1 user
GET http://localhost:9000/api/users/65508f1800976eaf92127b07 HTTP/1.1

### Delete user
DELETE http://localhost:9000/api/users/65508f1800976eaf92127b07 HTTP/1.1

###
PUT http://localhost:9000/api/users/6550927b0e7178d81b5f5bb2 HTTP/1.1
Content-Type: application/json

{
  "alumno": "cambio",
  "edad": 50,
  "cuenta": "20230000",
  "correo": "cambio@email.com"
}